import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notification from "@/app/components/Notification";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import AuthProvider from "./components/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AuthProvider>
				<body className={inter.className}>
					<Notification />
					<Navbar />
					{children}
					<Footer />
				</body>
			</AuthProvider>
		</html>
	);
}
